### ISSUE TITLE
Returns 101%

### ISSUE THREAD

**Issue by zamadatix** [SM-Wistful/BotDetection-Algorithm#1]
When detecting accounts as bots 101% is often returned https://www.reddit.com/r/tumblr/comments/7awb90/what/dpdsjmo/

**Comment by PaulieD** [comment]
Lmao, that is because perryochen (aka the bot that detects if something is a bot) is the account being queried. Since we know perryochen is a bot as its the bot detecting bot, we might as well have fun with it and say 101%

**Comment by SM-Wistful** [comment]
@PaulieD is absolutely right -- it's just a joke. Hopefully I can post the full source code soon to help clear up this kind of confusion ;)
