### ISSUE TITLE
Bot responds to a message that isn't !isbot

### ISSUE THREAD

**Issue by hkyq** [SM-Wistful/BotDetection-Algorithm#4]
https://www.reddit.com/r/Discord_Bots/comments/7tw7dk/download_or_programm_a_bot/dtfp0vn/

**Comment by mhall0808** [comment]
It appears that the bot searches for the words 'good bot' and replies to that.

I suggest changing the search term to only search the beginning of the string for these words, instead of anywhere in a sentence.

**Comment by SM-Wistful** [comment]
That is definitely a good idea. I ignored comments > 30 characters, but clearly it was not enough and there are still many false positives. I will add this feature when I update the code tonight.

**Comment by hkyq** [comment]
No longer in development, it seems.
